---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ovn_controller
  name: ovn_controller
spec:
  containers:
    - args:
      - "dumb-init"
      - "--single-child"
      - "--"
      env:
      - name: "LANG"
        value: "en_US.UTF-8"
      - name: "KOLLA_CONFIG_STRATEGY"
        value: "COPY_ALWAYS"
      - name: "PATH"
        value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - name: "container"
        value: "oci"
      - name: "HOME"
        value: "/root"
      - name: "HOSTNAME"
        value: "{{ ansible_hostname }}"
      command:
       - "kolla_start"
      name: ovn_controller
      image: quay.io/podified-antelope-centos9/openstack-ovn-controller:current-podified
      securityContext:
        privileged: true
        procMount: Unmasked
      volumeMounts:
        - mountPath: /var/lib/kolla/config_files/config.json
          name: var-lib-kolla-config_files-ovn_controller.json-host-0
          readOnly: true
        - mountPath: /run
          name: run-host-2
        - mountPath: /run/ovn
          name: var-lib-openvswitch-ovn-host-3
        - mountPath: /lib/modules
          name: lib-modules-host-5
          readOnly: true
        - mountPath: /openstack
          name: var-lib-openstack-healthchecks-ovn_controller-host-7
          readOnly: true
  hostNetwork: true
  volumes:
    - hostPath:
        path: /var/lib/kolla/config_files/ovn_controller.json
        type: File
      name: var-lib-kolla-config_files-ovn_controller.json-host-0
    - hostPath:
        path: /run
        type: Directory
      name: run-host-2
    - hostPath:
        path: /var/lib/openvswitch/ovn
        type: Directory
      name: var-lib-openvswitch-ovn-host-3
    - hostPath:
        path: /lib/modules
        type: Directory
      name: lib-modules-host-5
    - hostPath:
        path: /var/lib/openstack/healthchecks/ovn_controller
        type: Directory
      name: var-lib-openstack-healthchecks-ovn_controller-host-7
