apiVersion: ansibleee.openstack.org/v1alpha1
kind: OpenStackAnsibleEE
metadata:
  name: deploy-external-dataplane-compute
  namespace: openstack
spec:
  # We can specify either playbook, which will run with default ansible-runner options,
  # or args, which allows specify the whole command that we want to execute
  play: |

    - hosts: all
      tasks:
        - name: Enable edpm-repos
          shell: |
            rpm -q git || sudo yum -y install git
            sudo yum -y install python-setuptools python-requests python3-pip
            git clone https://git.openstack.org/openstack/tripleo-repos
            pushd tripleo-repos
            sudo python3 setup.py install
            popd
            sudo /usr/local/bin/tripleo-repos current-tripleo-dev

        - name: dnf install tmux
          shell: dnf -y install tmux

        - name: pip install sshuttle
          shell: pip install sshuttle

        - name: run sshuttle
          shell: tmux new-session -d -s sshuttle "sshuttle -r root@192.168.122.1 192.168.130.0/24"

    - name: Deploy EDPM facts playbook
      ansible.builtin.import_playbook: deploy-edpm-facts.yml

    - name: Deploy EDPM SELinux playbook
      ansible.builtin.import_playbook: deploy-edpm-selinux.yml

    - name: Deploy EDPM pre-network playbook
      ansible.builtin.import_playbook: deploy-edpm-pre-network.yml

    - name: Deploy EDPM network playbook
      ansible.builtin.import_playbook: deploy-edpm-network-configure.yml

    - name: Deploy EDPM network validation playbook
      ansible.builtin.import_playbook: deploy-edpm-network-validate.yml

    - name: Deploy EDPM install operating system playbook
      ansible.builtin.import_playbook: deploy-edpm-os-install.yml

    - name: Deploy EDPM configure operating system playbook
      ansible.builtin.import_playbook: deploy-edpm-os-configure.yml

    - name: Deploy EDPM run operating system playbook
      ansible.builtin.import_playbook: deploy-edpm-os-run.yml

    - name: Deploy EDPM install OpenStack playbook
      ansible.builtin.import_playbook: deploy-edpm-openstack-install.yml

    - name: Deploy EDPM configure OpenStack playbook
      ansible.builtin.import_playbook: deploy-edpm-openstack-configure.yml

    - name: Deploy EDPM run OpenStack playbook
      ansible.builtin.import_playbook: deploy-edpm-openstack-run.yml
  image: "quay.io/openstack-k8s-operators/openstack-ansibleee-runner:latest"
  inventory: |
    allovercloud:
      children:
        overcloud:
            children:
              Compute:
                hosts:
                  # Add additional computes here, and optionally drop localhost.
                  # Add host vars under the host_vars dir.
                  192.168.122.139:
                    ansible_ssh_user: root
                    ctlplane_ip: 192.168.24.100
                    internal_api_ip: 192.168.24.2
                    tenant_ip: 192.168.24.2
                    fqdn_internal_api: '{{ ansible_fqdn }}'
                vars:
                  chrony_ntp_servers:
                    - clock.redhat.com
                    - clock2.redhat.com

                  service_net_map:
                    nova_api_network: internal_api
                    nova_libvirt_network: internal_api

                  # edpm_network_config
                  # Default nic config template for a EDPM compute node
                  # These vars are edpm_network_config role vars
                  edpm_network_config_template: templates/net_config_bridge.j2
                  edpm_network_config_hide_sensitive_logs: false
                  #
                  # These vars are for the network config templates themselves and are
                  # considered EDPM network defaults.
                  neutron_physical_bridge_name: br-ex
                  neutron_public_interface_name: eth0
                  ctlplane_subnet_cidr: 24
                  ctlplane_gateway_ip: 192.168.122.1

                  # edpm_nodes_validation
                  edpm_nodes_validation_validate_controllers_icmp: false
                  edpm_nodes_validation_validate_gateway_icmp: false

                  # 99-standalone-vars
                  ctlplane_dns_nameservers:
                  - 192.168.122.1
                  dns_search_domains: []
                  edpm_nova_compute_DEFAULT_transport_url: rabbit://guest:ar3TXOAYMaznW29fRLj2ILXKs@standalone.ctlplane.localdomain:5672/?ssl=0
                  edpm_nova_compute_cache_memcache_servers: standalone.ctlplane.localdomain:11211
                  edpm_nova_compute_cinder_auth_url: http://192.168.24.3:5000/v3
                  edpm_nova_compute_cinder_password: ip3VDO3mq6JObAQqfekzt85kp
                  edpm_nova_compute_config_overrides:
                    DEFAULT:
                      oslo_messaging_notifications_transport_url: rabbit://guest:ar3TXOAYMaznW29fRLj2ILXKs@standalone.ctlplane.localdomain:5672/?ssl=0
                      transport_url: rabbit://guest:ar3TXOAYMaznW29fRLj2ILXKs@standalone.ctlplane.localdomain:5672/?ssl=0
                    cache:
                      memcache_servers: standalone.ctlplane.localdomain:11211
                    cinder:
                      auth_url: http://192.168.24.3:5000/v3
                      password: ip3VDO3mq6JObAQqfekzt85kp
                    neutron:
                      auth_type: v3password
                      auth_url: http://192.168.24.3:5000/v3
                      password: viaNg9cyAqS8N1ydQe7n3XkuM
                      project_domain_name: Default
                      project_name: service
                      region_name: regionOne
                      user_domain_name: Default
                      username: neutron
                    placement:
                      auth_type: password
                      auth_url: http://192.168.24.3:5000
                      password: Tnqq58zC6mD9O2jaC8xfiyt3M
                      project_domain_name: Default
                      project_name: service
                      region_name: regionOne
                      user_domain_name: Default
                      username: placement
                      valid_interfaces: internal
                    service_user:
                      auth_type: password
                      auth_url: http://192.168.24.3:5000
                      password: 59CnvTwMZcJfxCF9NU8bGWrcd
                      project_domain_name: Default
                      project_name: service
                      region_name: regionOne
                      send_service_user_token: 'True'
                      user_domain_name: Default
                      username: nova
                    vnc:
                      novncproxy_base_url: http://192.168.24.3:6080
                  edpm_nova_compute_neutron_auth_type: v3password
                  edpm_nova_compute_neutron_auth_url: http://192.168.24.3:5000/v3
                  edpm_nova_compute_neutron_password: viaNg9cyAqS8N1ydQe7n3XkuM
                  edpm_nova_compute_neutron_project_domain_name: Default
                  edpm_nova_compute_neutron_project_name: service
                  edpm_nova_compute_neutron_region_name: regionOne
                  edpm_nova_compute_neutron_user_domain_name: Default
                  edpm_nova_compute_neutron_username: neutron
                  edpm_nova_compute_oslo_messaging_notifications_transport_url: rabbit://guest:ar3TXOAYMaznW29fRLj2ILXKs@standalone.ctlplane.localdomain:5672/?ssl=0
                  edpm_nova_compute_placement_auth_type: password
                  edpm_nova_compute_placement_auth_url: http://192.168.24.3:5000
                  edpm_nova_compute_placement_password: Tnqq58zC6mD9O2jaC8xfiyt3M
                  edpm_nova_compute_placement_project_domain_name: Default
                  edpm_nova_compute_placement_project_name: service
                  edpm_nova_compute_placement_region_name: regionOne
                  edpm_nova_compute_placement_user_domain_name: Default
                  edpm_nova_compute_placement_username: placement
                  edpm_nova_compute_placement_valid_interfaces: internal
                  edpm_nova_compute_service_user_auth_type: password
                  edpm_nova_compute_service_user_auth_url: http://192.168.24.3:5000
                  edpm_nova_compute_service_user_password: 59CnvTwMZcJfxCF9NU8bGWrcd
                  edpm_nova_compute_service_user_project_domain_name: Default
                  edpm_nova_compute_service_user_project_name: service
                  edpm_nova_compute_service_user_region_name: regionOne
                  edpm_nova_compute_service_user_send_service_user_token: true
                  edpm_nova_compute_service_user_user_domain_name: Default
                  edpm_nova_compute_service_user_username: nova
                  edpm_nova_compute_vnc_novncproxy_base_url: http://192.168.24.3:6080
                  edpm_ovn_dbs:
                  - 192.168.24.1
            vars:
                edpm_ovn_controller_image: quay.io/tripleomastercentos9/openstack-ovn-controller:current-tripleo
                gather_facts: false
                enable_debug: false
                # SELinux module
                edpm_selinux_mode: enforcing
                undercloud_hosts_entries: []
                # edpm_hosts_entries role
                extra_hosts_entries: []
                vip_hosts_entries: []
                hosts_entries: []
                hosts_entry: []
                plan: overcloud

  env:
    - name: ANSIBLE_FORCE_COLOR
      value: "True"
    - name: ANSIBLE_SSH_ARGS
      value: "-C -o ControlMaster=auto -o ControlPersist=80s"
    - name: ANSIBLE_ENABLE_TASK_DEBUGGER
      value: "True"
  extraMounts:
    - volumes:
        - name: ssh-key
          secret:
            secretName: ansibleee-ssh-key-secret
            items:
              - key: private_ssh_key
                path: ssh_key
      mounts:
        - name: ssh-key
          mountPath: /runner/env/ssh_key
          subPath: ssh_key

