---
apiVersion: ansibleee.openstack.org/v1alpha1
kind: OpenStackAnsibleEE
metadata:
  name: deploy-external-dataplane-compute
  namespace: openstack
spec:
  # We can specify either playbook, which will run with default ansible-runner options,
  # or args, which allows specify the whole command that we want to execute
  play: |

    - hosts: all
      tasks:
        - name: Enable tripleo-repos
          shell: |
            rpm -q git || sudo yum -y install git
            sudo yum -y install python-setuptools python-requests python3-pip
            git clone https://git.openstack.org/openstack/tripleo-repos
            pushd tripleo-repos
            sudo python3 setup.py install
            popd
            sudo /usr/local/bin/tripleo-repos current-tripleo-dev

    - name: Deploy EDPM facts playbook
      ansible.builtin.import_playbook: deploy-edpm-facts.yml

    - name: Deploy EDPM pre-network playbook
      ansible.builtin.import_playbook: deploy-edpm-pre-network.yml

    - name: Deploy EDPM network playbook
      ansible.builtin.import_playbook: deploy-edpm-network-configure.yml

    - name: Deploy EDPM network validation playbook
      ansible.builtin.import_playbook: deploy-edpm-network-validate.yml

    - name: Deploy EDPM install operating system playbook
      ansible.builtin.import_playbook: deploy-edpm-os-install.yml

    - name: Deploy EDPM configure operating system playbook
      ansible.builtin.import_playbook: deploy-edpm-os-configure.yml

    - name: Deploy EDPM run operating system playbook
      ansible.builtin.import_playbook: deploy-edpm-os-run.yml

    - name: Deploy EDPM install OpenStack playbook
      ansible.builtin.import_playbook: deploy-edpm-openstack-install.yml

    - name: Deploy EDPM configure OpenStack playbook
      ansible.builtin.import_playbook: deploy-edpm-openstack-configure.yml

    - name: Deploy EDPM run OpenStack playbook
      ansible.builtin.import_playbook: deploy-edpm-openstack-run.yml
  image: "_OPENSTACK_RUNNER_IMG_"
  inventory: |
    allovercloud:
      children:
        overcloud:
            children:
              Compute:
                hosts:
                  # Add additional computes here, and optionally drop localhost.
                  # Add host vars under the host_vars dir.
                  _COMPUTE_IP_:
                    ansible_ssh_user: root
                    ctlplane_ip: _COMPUTE_IP_
                    internal_api_ip: 172.17.0.100
                    storage_ip: 172.18.0.100
                    tenant_ip: 172.10.0.100
                    fqdn_internal_api: '{{ ansible_fqdn }}'
                vars:
                  service_net_map:
                    nova_api_network: internal_api
                    nova_libvirt_network: internal_api

                  # edpm_network_config
                  # Default nic config template for a EDPM compute node
                  # These vars are edpm_network_config role vars
                  edpm_network_config_template: _EDPM_NETWORK_CONFIG_TEMPLATE_
                  edpm_network_config_hide_sensitive_logs: false
                  #
                  # These vars are for the network config templates themselves and are
                  # considered EDPM network defaults.
                  neutron_physical_bridge_name: br-ex
                  neutron_public_interface_name: eth0
                  ctlplane_mtu: 1500
                  ctlplane_subnet_cidr: 24
                  ctlplane_gateway_ip: 192.168.122.1
                  ctlplane_host_routes:
                  - ip_netmask: 0.0.0.0/0
                    next_hop: 192.168.122.1
                  external_mtu: 1500
                  external_vlan_id: 44
                  external_cidr: '24'
                  external_host_routes: []
                  internal_api_mtu: 1500
                  internal_api_vlan_id: 20
                  internal_api_cidr: '24'
                  internal_api_host_routes: []
                  storage_mtu: 1500
                  storage_vlan_id: 21
                  storage_cidr: '24'
                  storage_host_routes: []
                  tenant_mtu: 1500
                  tenant_vlan_id: 22
                  tenant_cidr: '24'
                  tenant_host_routes: []
                  role_networks:
                  - InternalApi
                  - Storage
                  - Tenant
                  networks_lower:
                    External: external
                    InternalApi: internal_api
                    Storage: storage
                    Tenant: tenant

                  # edpm_nodes_validation
                  edpm_nodes_validation_validate_controllers_icmp: false
                  edpm_nodes_validation_validate_gateway_icmp: false

                  edpm_ovn_metadata_agent_DEFAULT_transport_url: '_EDPM_OVN_METADATA_AGENT_TRANSPORT_URL_'
                  edpm_ovn_metadata_agent_metadata_agent_ovn_ovn_sb_connection: '_EDPM_OVN_METADATA_AGENT_SB_CONNECTION_'
                  edpm_ovn_metadata_agent_metadata_agent_DEFAULT_nova_metadata_host: '_EDPM_OVN_METADATA_AGENT_NOVA_METADATA_HOST_'
                  edpm_ovn_metadata_agent_metadata_agent_DEFAULT_metadata_proxy_shared_secret: '_EDPM_OVN_METADATA_AGENT_PROXY_SHARED_SECRET_'
                  edpm_ovn_metadata_agent_DEFAULT_bind_host: '_EDPM_OVN_METADATA_AGENT_BIND_HOST_'
                  epdm_chrony_ntp_servers:
                  - '_EDPM_CHRONY_NTP_SERVER_'

                  # 99-standalone-vars
                  ctlplane_dns_nameservers:
                  - 192.168.122.1
                  dns_search_domains: []
                  edpm_nova_compute_reserved_host_memory: 2048
                  edpm_nova_compute_DEFAULT_transport_url: '_EDPM_NOVA_COMPUTE_TRANSPORT_URL_'
                  edpm_nova_compute_cache_memcache_servers: standalone.ctlplane.localdomain:11211
                  edpm_nova_compute_cinder_auth_url: http://keystone-internal.openstack.svc:5000/v3
                  edpm_nova_compute_cinder_password: 12345678
                  edpm_nova_compute_config_overrides:
                    DEFAULT:
                      oslo_messaging_notifications_transport_url: '_EDPM_NOVA_NOTIFICATIONS_TRANSPORT_URL_'
                      transport_url: '_EDPM_NOVA_COMPUTE_TRANSPORT_URL_'
                    cache:
                      memcache_servers: standalone.ctlplane.localdomain:11211
                    cinder:
                      auth_url: http://keystone-internal.openstack.svc:5000/v3
                      password: 12345678
                    neutron:
                      auth_type: v3password
                      auth_url: http://keystone-internal.openstack.svc:5000/v3
                      password: 12345678
                      project_domain_name: Default
                      project_name: service
                      region_name: regionOne
                      user_domain_name: Default
                      username: neutron
                    placement:
                      auth_type: password
                      auth_url: http://keystone-internal.openstack.svc:5000/v3
                      password: 12345678
                      project_domain_name: Default
                      project_name: service
                      region_name: regionOne
                      user_domain_name: Default
                      username: placement
                      valid_interfaces: internal
                    service_user:
                      auth_type: password
                      auth_url: http://keystone-internal.openstack.svc:5000/v3
                      password: 12345678
                      project_domain_name: Default
                      project_name: service
                      region_name: regionOne
                      send_service_user_token: 'True'
                      user_domain_name: Default
                      username: nova
                    vnc:
                      novncproxy_base_url: http://192.168.24.3:6080
                  edpm_nova_compute_neutron_auth_type: v3password
                  edpm_nova_compute_neutron_auth_url: http://keystone-internal.openstack.svc:5000/v3
                  edpm_nova_compute_neutron_password: 12345678
                  edpm_nova_compute_neutron_project_domain_name: Default
                  edpm_nova_compute_neutron_project_name: service
                  edpm_nova_compute_neutron_region_name: regionOne
                  edpm_nova_compute_neutron_user_domain_name: Default
                  edpm_nova_compute_neutron_username: neutron
                  edpm_nova_compute_oslo_messaging_notifications_transport_url: '_EDPM_NOVA_NOTIFICATIONS_TRANSPORT_URL_'
                  edpm_nova_compute_placement_auth_type: password
                  edpm_nova_compute_placement_auth_url: http://keystone-internal.openstack.svc:5000
                  edpm_nova_compute_placement_password: 12345678
                  edpm_nova_compute_placement_project_domain_name: Default
                  edpm_nova_compute_placement_project_name: service
                  edpm_nova_compute_placement_region_name: regionOne
                  edpm_nova_compute_placement_user_domain_name: Default
                  edpm_nova_compute_placement_username: placement
                  edpm_nova_compute_placement_valid_interfaces: internal
                  edpm_nova_compute_service_user_auth_type: password
                  edpm_nova_compute_service_user_auth_url: http://keystone-internal.openstack.svc:5000
                  edpm_nova_compute_service_user_password: 12345678
                  edpm_nova_compute_service_user_project_domain_name: Default
                  edpm_nova_compute_service_user_project_name: service
                  edpm_nova_compute_service_user_region_name: regionOne
                  edpm_nova_compute_service_user_send_service_user_token: true
                  edpm_nova_compute_service_user_user_domain_name: Default
                  edpm_nova_compute_service_user_username: nova
                  edpm_nova_compute_vnc_novncproxy_base_url: http://192.168.24.3:6080
                  edpm_ovn_dbs:
                  - _EDPM_OVN_DBS_
            vars:
                registry_name: "quay.io"
                registry_namespace: "podified-zed-centos9"
                image_tag: "current-podified"
                edpm_ovn_controller_agent_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-ovn-controller:{{ image_tag }}"
                edpm_iscsid_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-iscsid:{{ image_tag }}"
                edpm_logrotate_crond_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-cron:{{ image_tag }}"
                edpm_nova_compute_container_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-nova-compute:{{ image_tag }}"
                edpm_nova_libvirt_container_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-nova-libvirt:{{ image_tag }}"
                edpm_ovn_metadata_agent_image: "{{ registry_name }}/{{ registry_namespace }}/openstack-neutron-metadata-agent-ovn:{{ image_tag }}"

                gather_facts: false
                enable_debug: false
                # edpm firewall, change the allowed CIDR if needed
                edpm_sshd_configure_firewall: true
                edpm_sshd_allowed_ranges: _EDPM_SSHD_ALLOWED_RANGES_
                # SELinux module
                edpm_selinux_mode: enforcing
                undercloud_hosts_entries: []
                # edpm_hosts_entries role
                extra_hosts_entries:
                - 172.17.0.80 glance-internal.openstack.svc neutron-internal.openstack.svc cinder-internal.openstack.svc nova-internal.openstack.svc placement-internal.openstack.svc keystone-internal.openstack.svc
                - 172.17.0.85 rabbitmq.openstack.svc
                - 172.17.0.86 rabbitmq-cell1.openstack.svc
                vip_hosts_entries: []
                hosts_entries: []
                hosts_entry: []
                plan: overcloud

  env:
    - name: ANSIBLE_FORCE_COLOR
      value: "True"
    - name: ANSIBLE_SSH_ARGS
      value: "-C -o ControlMaster=auto -o ControlPersist=80s"
    - name: ANSIBLE_ENABLE_TASK_DEBUGGER
      value: "True"
  extraMounts:
    - volumes:
        - name: ssh-key
          secret:
            secretName: dataplane-ansible-ssh-private-key-secret
            items:
              - key: ssh-privatekey
                path: ssh_key
      mounts:
        - name: ssh-key
          mountPath: /runner/env/ssh_key
          subPath: ssh_key
