#!/bin/bash
#
# Copyright 2024 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Generates random secrets and writes them to .secrets.env in Make-compatible
# format. Skips generation if the file already exists unless
# REGENERATE_SECRETS=true is set.

set -eu

SECRETS_FILE="${SECRETS_FILE:-.secrets.env}"

if [ -f "${SECRETS_FILE}" ] && [ "${REGENERATE_SECRETS:-false}" != "true" ]; then
    echo "Secrets file ${SECRETS_FILE} already exists, skipping generation."
    echo "Set REGENERATE_SECRETS=true to force regeneration."
    exit 0
fi

gen_password() {
    openssl rand -hex 16
}

gen_short_hex() {
    openssl rand -hex "$1"
}

gen_base64_key() {
    local bytes="${1:-32}"
    head --bytes="${bytes}" /dev/urandom | base64 -w 0
}

cat > "${SECRETS_FILE}" <<EOF
# Auto-generated by scripts/gen-secrets.sh -- do not edit, do not commit.
# Delete this file (or run "make secrets_clean") to regenerate all secrets.

# OpenStack service passwords (osp-secret fields)
ADMIN_PASSWORD ?= $(gen_password)
AODH_PASSWORD ?= $(gen_password)
BARBICAN_PASSWORD ?= $(gen_password)
CEILOMETER_PASSWORD ?= $(gen_password)
CLOUDKITTY_PASSWORD ?= $(gen_password)
DB_ROOT_PASSWORD ?= $(gen_password)
DATABASE_PASSWORD ?= $(gen_password)
DESIGNATE_PASSWORD ?= $(gen_password)
PLACEMENT_PASSWORD ?= $(gen_password)
GLANCE_PASSWORD ?= $(gen_password)
NEUTRON_PASSWORD ?= $(gen_password)
CINDER_PASSWORD ?= $(gen_password)
IRONIC_PASSWORD ?= $(gen_password)
IRONIC_INSPECTOR_PASSWORD ?= $(gen_password)
OCTAVIA_PASSWORD ?= $(gen_password)
OCTAVIA_HEARTBEAT_KEY ?= $(gen_password)
NOVA_PASSWORD ?= $(gen_password)
MANILA_PASSWORD ?= $(gen_password)
HEAT_PASSWORD ?= $(gen_password)
HEAT_STACK_DOMAIN_ADMIN_PASSWORD ?= $(gen_password)
SWIFT_PASSWORD ?= $(gen_password)
WATCHER_PASSWORD ?= $(gen_password)
LIBVIRT_PASSWORD ?= $(gen_password)
OCTAVIA_CA_PASSPHRASE ?= $(gen_password)

# Special-format encryption keys
BARBICAN_SIMPLE_CRYPTO_ENCRYPTION_KEY ?= $(gen_base64_key 32)
HEAT_AUTH_ENCRYPTION_KEY ?= $(gen_short_hex 16)
METADATA_SHARED_SECRET ?= $(gen_short_hex 5)
KEYSTONE_FEDERATION_CLIENT_SECRET ?= $(gen_base64_key 24)
KEYSTONE_FEDERATION_CRYPTO_PASSPHRASE ?= $(gen_short_hex 8)

# CRC / OCP cluster passwords
KUBEADMIN_PWD ?= $(gen_password)
OCP_ADMIN_PASSWD ?= $(gen_password)

# BMAAS / Redfish credentials
BMAAS_REDFISH_PASSWORD ?= $(gen_password)

# EDPM compute node root password
EDPM_ROOT_PASSWORD ?= $(gen_password)

# Ceph RGW Keystone password
RGW_PASS ?= $(gen_password)

# FreeIPA admin password
DEVSETUP_IPA_ADMIN_PASSWORD ?= $(gen_short_hex 16)

# MetalLB BGP peer password
BGP_PEER_PASSWORD ?= $(gen_short_hex 8)

# Loki S3 credentials
LOKI_S3_ACCESS_KEY_ID ?= $(gen_password)
LOKI_S3_ACCESS_KEY_SECRET ?= $(gen_password)
EOF

chmod 600 "${SECRETS_FILE}"
echo "Generated secrets in ${SECRETS_FILE}"
