---
- name: Include OS-specific variables
  tags:
    - always
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yaml"

- name: Install build dependencies
  become: "{{ false if ansible_os_family == 'Darwin' else true }}"
  tags:
    - dependencies
  ansible.builtin.package:
    name: "{{ tools_packages }}"
    state: present

- name: Set opm download url suffix
  tags:
    - opm
  ansible.builtin.set_fact:
    opm_url_suffix: "latest/download"
  when: opm_version is undefined or opm_version == "latest"

- name: Set opm download url suffix
  tags:
    - opm
  ansible.builtin.set_fact:
    opm_url_suffix: "download/{{ opm_version }}"
  when: opm_version is defined and opm_version != "latest"

- name: Create $HOME/bin dir
  tags:
    - always
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/bin"
    state: directory
    mode: '0755'

- name: Download opm
  tags:
    - opm
  ansible.builtin.get_url:
    url:
      "https://github.com/operator-framework/operator-registry/releases/\
      {{ opm_url_suffix }}/{{ os_name }}-{{ arch }}-opm"
    dest: "{{ lookup('env', 'HOME') }}/bin/opm"
    mode: '0755'
    timeout: 30

- name: Set oc-mirror download url
  tags:
    - oc_mirror
  ansible.builtin.set_fact:
    oc_mirror_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ oc_mirror_version }}/oc-mirror.tar.gz"

- name: Download and extract oc-mirror
  tags:
    - oc_mirror
  ansible.builtin.unarchive:
    src: "{{ oc_mirror_url }}"
    dest: "{{ lookup('env', 'HOME') }}/bin/"
    remote_src: true

- name: Make oc-mirror executable
  tags:
    - oc_mirror
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/bin/oc-mirror"
    mode: '0755'

- name: Download operator-sdk
  tags:
    - operator_sdk
  ansible.builtin.get_url:
    url:
      "https://github.com/operator-framework/operator-sdk/releases/download/\
      {{ sdk_version }}/operator-sdk_{{ os_name }}_{{ arch }}"
    dest: "{{ lookup('env', 'HOME') }}/bin/operator-sdk"
    mode: '0755'
    force: true
    timeout: 30

- name: Download and extract kustomize
  tags:
    - kustomize
  ansible.builtin.unarchive:
    src:
      "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F\
      {{ kustomize_version }}/kustomize_{{ kustomize_version }}_{{ os_name }}_{{ arch }}.tar.gz"
    dest: "{{ lookup('env', 'HOME') }}/bin/"
    remote_src: true

- name: Download kubectl
  tags:
    - kubectl
  ansible.builtin.get_url:
    url:
      "https://dl.k8s.io/release/{{ kubectl_version }}/bin/{{ os_name }}/{{ arch }}/kubectl"
    dest: "{{ lookup('env', 'HOME') }}/bin/kubectl"
    mode: '0755'
    timeout: 30

- name: Download kuttl
  tags:
    - kuttl
  ansible.builtin.get_url:
    url:
      "https://github.com/kudobuilder/kuttl/releases/download/v{{ kuttl_version }}/\
      kubectl-kuttl_{{ kuttl_version }}_{{ os_name }}_{{ ansible_architecture }}"
    dest: "{{ lookup('env', 'HOME') }}/bin/kubectl-kuttl"
    mode: '0755'
    timeout: 30

- name: Download chainsaw
  tags:
    - chainsaw
  ansible.builtin.unarchive:
    src:
      "https://github.com/kyverno/chainsaw/releases/download/v{{ chainsaw_version }}/\
      chainsaw_{{ os_name }}_{{ arch }}.tar.gz"
    dest: "{{ lookup('env', 'HOME') }}/bin/"
    remote_src: true
    extra_opts:
      - "--exclude"
      - "README.md"
      - "--exclude"
      - "LICENSE"

- name: Install yq from GitHub
  tags:
    - yq
  when: ansible_os_family != 'Darwin'
  block:
    - name: Download and extract yq
      ansible.builtin.unarchive:
        src:
          https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64.tar.gz
        dest: "{{ lookup('env', 'HOME') }}/bin/"
        remote_src: true
        mode: '0755'

    - name: Link yq_linux_amd64 as yq
      ansible.builtin.file:
        src: "{{ lookup('env', 'HOME') }}/bin/yq_linux_amd64"
        dest: "{{ lookup('env', 'HOME') }}/bin/yq"
        state: link

- name: Set proper golang on the system
  become: "{{ false if ansible_os_family == 'Darwin' else true }}"
  tags:
    - golang
  block:
    - name: Deinstall golang
      ansible.builtin.package:
        state: absent
        name: "{{ golang_packages }}"

    - name: Delete old go version installed from upstream
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /usr/local/go
        - "{{ lookup('env', 'HOME') }}/bin/go"
        - "{{ lookup('env', 'HOME') }}/bin/gofmt"
        - /usr/local/bin/go
        - /usr/local/bin/gofmt

    - name: Ensure golang install directory exists
      ansible.builtin.file:
        path: "{{ golang_install_dir }}"
        state: directory
        mode: '0755'

    - name: Download and extract golang
      ansible.builtin.unarchive:
        src: "https://golang.org/dl/go{{ go_version }}.{{ os_name }}-{{ arch }}.tar.gz"
        dest: "{{ golang_install_dir }}"
        remote_src: true
        extra_opts:
          - "--exclude"
          - "go/misc"
          - "--exclude"
          - "go/test"

    - name: Set alternatives link to installed go version
      ansible.builtin.shell: |
        set -e
        update-alternatives --install /usr/local/bin/{{ item }} {{ item }} \
        /usr/local/go/bin/{{ item }} 1
      with_items:
        - go
        - gofmt
      changed_when: true
      when: ansible_os_family != 'Darwin'

    - name: Symlink go binaries into $HOME/bin
      ansible.builtin.file:
        src: "{{ golang_install_dir }}/go/bin/{{ item }}"
        dest: "{{ lookup('env', 'HOME') }}/bin/{{ item }}"
        state: link
      with_items:
        - go
        - gofmt
      when: ansible_os_family == 'Darwin'

- name: Suggestions
  tags:
    - always
  ansible.builtin.debug:
    msg: >-
      When move from package to upstream version,
      make sure to clean shell cache using
      `hash -d go` (bash) or `rehash` (zsh).
      On macOS, ensure $HOME/bin is in your PATH.
