---
# Released version of the opm package (can be set to 'latest')
opm_version: v1.30.0

# operator-sdk version to use (must be specific version)
sdk_version: v1.31.0

# golang version
go_version: 1.20.14

# kustomize version to use (must be specific version)
kustomize_version: v5.0.3
