---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  labels:
    app.kubernetes.io/name: openstackdataplaneservice
    app.kubernetes.io/instance: openstackdataplaneservice-repo-setup
    app.kubernetes.io/part-of: dataplane-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: install_yamls
  name: repo-setup
spec:
  label: dataplane-deployment-repo-setup
  play: |
    - hosts: all
      strategy: linear
      tasks:
        - name: Install Python dependencies
          ansible.builtin.package:
            name:
              - git
              - python-setuptools
              - python-requests
              - python3-pip
            state: present
          become: True
        - name: Install repo-setup directly from github
          ansible.builtin.pip:
            name: git+https://github.com/openstack-k8s-operators/repo-setup
          become: True
        - name: Enable podified-repos
          ansible.builtin.shell: |
            sudo /usr/local/bin/repo-setup current-podified-dev
          changed_when: True
          become: True
