---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  labels:
    app.kubernetes.io/name: openstackdataplaneservice
    app.kubernetes.io/instance: openstackdataplaneservice-repo-setup
    app.kubernetes.io/part-of: openstack-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: install_yamls
  name: repo-setup
spec:
  label: repo-setup
  playbookContents: |
    - hosts: all
      strategy: linear
      tasks:
        - name: Install repo-setup tool
          become: true
          ansible.builtin.shell: |
            set -euxo pipefail
            pushd /var/tmp
            curl -sL https://github.com/openstack-k8s-operators/repo-setup/archive/refs/heads/main.tar.gz | tar -xz
            pushd repo-setup-main
            python3 -m venv ./venv
            PBR_VERSION=0.0.0 ./venv/bin/pip install ./

        - name: Enable podified-repos for CentOS Stream 9
          become: true
          when: ansible_distribution_major_version | int != 10
          ansible.builtin.shell: |
            set -euxo pipefail
            /var/tmp/repo-setup-main/venv/bin/repo-setup current-podified -b antelope

        - name: Enable podified-repos for CentOS Stream 10
          become: true
          when: ansible_distribution_major_version | int == 10
          ansible.builtin.shell: |
            set -euxo pipefail
            /var/tmp/repo-setup-main/venv/bin/repo-setup current -b master

        - name: Clean up repo-setup source
          become: true
          ansible.builtin.file:
            path: /var/tmp/repo-setup-main
            state: absent
